// Disposable local CMS fixtures; no live accounts, club data or subscriptions.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
let clubs=[{id:1,slug:'barver',name:'SV Barver Darts',tagline:'Vier Mannschaften. Ein Verein.',about:'',contact:'',accent:'#176b56',logoId:null,published:true,version:1,teams:[{key:'A',name:'Barver A'},{key:'B',name:'Barver B'}],darts:{enabled:true,leagues:[]}},{id:2,slug:'musterverein',name:'Musterverein',tagline:'Gemeinsam spielen',about:'Unser Verein',contact:'Vereinsheim',accent:'#ffffff',logoId:null,published:false,version:1,teams:[],darts:{enabled:false,leagues:[]}}],posts=[],users=[],revisions=new Map(),rejectSave=false;
const copy=x=>JSON.parse(JSON.stringify(x));
function response(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'}).end(JSON.stringify(data));}
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost'),p=url.pathname;
  if(p.startsWith('/api/v1/cms')){
    const route=p.slice('/api/v1/cms'.length);let body={};if(['POST','PUT'].includes(req.method)){let data='';for await(const chunk of req)data+=chunk;body=JSON.parse(data||'{}');}
    if(route==='/login'){res.setHeader('Set-Cookie','cms_fixture=owner; HttpOnly; SameSite=Strict; Path=/');return response(res,200,{ok:true});}
    if(route==='/session'){if(req.method==='DELETE'){res.setHeader('Set-Cookie','cms_fixture=; Max-Age=0; Path=/');return response(res,200,{ok:true});}return req.headers.cookie?.includes('cms_fixture=owner')?response(res,200,{owner:true,username:'Administration'}):response(res,401,{detail:'Bitte anmelden.'});}
    if(route==='/clubs'){if(req.method==='POST'){const club={teams:[],darts:{enabled:false,leagues:[]},id:clubs.length+1,tagline:'',about:'',contact:'',accent:'#176b56',logoId:null,published:false,version:1,...body};clubs.push(club);return response(res,201,club);}return response(res,200,{clubs});}
    const match=route.match(/^\/clubs\/(\d+)(.*)$/);if(match){const id=Number(match[1]),tail=match[2],club=clubs.find(club=>club.id===id);
      if(tail===''&&req.method==='PUT'){Object.assign(club,{...body,logoId:body.logo_id,version:club.version+1});return response(res,200,club);}
      if(tail==='/darts/preview')return response(res,200,{roundCount:18,teams:[{id:789,name:'Musterverein A'},{id:900,name:'DC Gegner A'}]});
      if(tail==='/darts'&&req.method==='PUT'){club.darts={enabled:body.enabled,leagues:body.leagues};club.version++;return response(res,200,club);}
      if(tail==='/media')return response(res,200,{media:[]});
      if(tail==='/users'){if(req.method==='POST'){users.push({id:users.length+1,clubId:id,username:body.username,active:true});return response(res,201,{id:users.length});}return response(res,200,{users:users.filter(user=>user.clubId===id)});}
      if(/^\/users\/\d+$/.test(tail)){const user=users.find(user=>user.id===Number(tail.split('/')[2]));user.active=body.active;return response(res,200,{ok:true});}
      if(tail==='/posts'){if(req.method==='POST'){const post={id:posts.length+1,clubId:id,draft:copy(body),published:null,publishAt:null,expiresAt:null,version:1,publishedVersion:null,updatedAt:new Date().toISOString()};posts.push(post);revisions.set(post.id,[{version:1,draft:copy(body),action:'saved',createdAt:post.updatedAt}]);return response(res,201,post);}return response(res,200,{posts:posts.filter(post=>post.clubId===id)});}
      const edit=tail.match(/^\/posts\/(\d+)(.*)$/);if(edit){const post=posts.find(post=>post.id===Number(edit[1])),action=edit[2];if(action==='/revisions')return response(res,200,{revisions:revisions.get(post.id).map(({draft,...revision})=>revision).reverse()});if(rejectSave){rejectSave=false;return response(res,409,{detail:'Der Beitrag wurde inzwischen geändert. Bitte neu laden; dein Text bleibt im Formular.'});}if(action==='')post.draft=copy(body);else if(action==='/publish'){post.published=copy(post.draft);post.publishAt=body.publish_at||new Date().toISOString();post.expiresAt=body.expires_at;post.publishedVersion=post.version+1;}else if(action==='/unpublish'){post.published=null;post.publishAt=null;post.expiresAt=null;post.publishedVersion=null;}else if(action==='/restore')post.draft=copy(revisions.get(post.id).find(item=>item.version===body.revision).draft);post.version++;post.updatedAt=new Date().toISOString();revisions.get(post.id).push({version:post.version,draft:copy(post.draft),action:action==='/restore'?'restored':'saved',createdAt:post.updatedAt});return response(res,200,post);}
    }
    const site=route.match(/^\/sites\/([^/]+)(.*)$/);if(site){const club=clubs.find(club=>club.slug===site[1]);if(!club?.published)return response(res,404,{detail:'Verein nicht gefunden.'});if(!site[2])return response(res,200,{...club,logo:null});const published=posts.filter(post=>post.clubId===club.id&&post.published&&Date.parse(post.publishAt)<=Date.now()&&(!post.expiresAt||Date.parse(post.expiresAt)>Date.now())).map(post=>({id:post.id,...post.published,publishedAt:post.publishAt,image:null,href:`/vereine/${club.slug}/beitraege/${post.id}`}));if(site[2]==='/posts')return response(res,200,{posts:published.filter(post=>url.searchParams.has('team')?(post.team_keys||[]).includes(url.searchParams.get('team')):post.show_home!==false).map(post=>({...post,showHome:post.show_home!==false,teamKeys:post.team_keys||[]}))});const post=published.find(post=>post.id===Number(site[2].split('/')[2]));return response(res,post?200:404,post||{detail:'Nicht gefunden.'});}
    return response(res,404,{});
  }
  const file=p==='/cms'?'/cms.html':p.startsWith('/vereine/')?'/cms-site.html':p;
  const target=path.resolve(root,'.'+file);if(!target.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(target,(error,data)=>{res.writeHead(error?404:200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'})[path.extname(target)]||'application/octet-stream'}).end(error?'Not found':data);});
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
  const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
  try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
    await page.goto(origin+'/cms');await page.locator('#loginForm input[name=username]').fill('owner');await page.locator('#loginForm input[name=password]').fill('fixture-test-password');await page.getByRole('button',{name:'Anmelden',exact:true}).click();await page.locator('#workspace').waitFor();await page.locator('#globalStatus').waitFor({state:'hidden'});
    assert.equal(await page.evaluate(()=>sessionStorage.length),0,'passwords are not kept in browser storage');
    if(process.env.CMS_SCREENSHOT)await page.screenshot({path:process.env.CMS_SCREENSHOT});
    await page.getByRole('button',{name:'+ Beitrag schreiben',exact:true}).click();const hostile='<img src=x onerror="window.cmsXss=1">';await page.locator('#postShowHome').uncheck();await page.locator('#postTeams input[value=A]').check();await page.locator('#postTitle').fill('Training am Dienstag');await page.locator('#postSummary').fill('Neuigkeiten für unser Team');await page.locator('#postBody').fill('Absatz eins.\n\n'+hostile);assert.equal(await page.locator('#publishPost').isEnabled(),false);await page.getByRole('button',{name:'Vorschau',exact:true}).click();await page.locator('#previewDialog').waitFor();assert.match(await page.locator('#previewContent').innerText(),/onerror/);assert.equal(await page.evaluate(()=>window.cmsXss),undefined);await page.locator('[data-close=previewDialog]').click();
    await page.getByRole('button',{name:'Entwurf speichern',exact:true}).click();await page.getByText('Entwurf gespeichert. Die öffentliche Fassung bleibt unverändert.',{exact:true}).waitFor();assert.equal(posts[0].published,null);await page.getByRole('button',{name:'Jetzt veröffentlichen',exact:true}).click();await page.getByText('Beitrag veröffentlicht.',{exact:true}).waitFor();assert.equal(posts[0].published.title,'Training am Dienstag');assert.equal(posts[0].published.show_home,false);assert.deepEqual(posts[0].published.team_keys,['A']);assert.equal((await (await page.request.get(origin+'/api/v1/cms/sites/barver/posts')).json()).posts.length,0);assert.equal((await (await page.request.get(origin+'/api/v1/cms/sites/barver/posts?team=A')).json()).posts.length,1);
    await page.locator('#postTitle').fill('Neuer privater Entwurf');rejectSave=true;await page.getByRole('button',{name:'Entwurf speichern',exact:true}).click();await page.locator('#postStatus.error').waitFor();assert.equal(await page.locator('#postTitle').inputValue(),'Neuer privater Entwurf','conflicts preserve typed content');assert.equal(posts[0].published.title,'Training am Dienstag');assert.equal(await page.locator('#publishPost').isEnabled(),false);await page.getByRole('button',{name:'Entwurf speichern',exact:true}).click();await page.getByText('Entwurf gespeichert. Die öffentliche Fassung bleibt unverändert.',{exact:true}).waitFor();assert.equal(posts[0].published.title,'Training am Dienstag');
    const tomorrow=new Date(Date.now()+86400000);const local=new Date(tomorrow.getTime()-tomorrow.getTimezoneOffset()*60000).toISOString().slice(0,16);await page.locator('#publishAt').fill(local);await page.locator('#publishAt').dispatchEvent('change');await page.getByRole('button',{name:'Veröffentlichung planen',exact:true}).click();await page.getByText('Veröffentlichung geplant. Sie startet automatisch.',{exact:true}).waitFor();assert.equal(await page.locator('#postState').innerText(),'Geplant');
    await page.locator('#history summary').click();await page.locator('.revision-row').first().waitFor();await page.locator('.revision-row').last().getByRole('button').click();await page.getByText('Version als Entwurf wiederhergestellt. Die öffentliche Fassung bleibt unverändert.',{exact:true}).waitFor();assert.equal(await page.locator('#postTitle').inputValue(),'Training am Dienstag');assert.equal(posts[0].published.title,'Neuer privater Entwurf');
    await page.locator('#clubChoice').selectOption('2');await page.locator('#clubLabel').filter({hasText:'Musterverein'}).waitFor();await page.locator('#globalStatus').waitFor({state:'hidden'});assert.equal(await page.locator('#recentPosts .post-recent').count(),0,'different clubs never mix their posts');assert.equal(await page.locator('#dartsAdmin').isVisible(),false,'Barver modules are not offered to other clubs');
    await page.getByRole('button',{name:'Vereinsseite',exact:true}).click();await page.getByRole('button',{name:'+ Mannschaft hinzufügen',exact:true}).click();await page.locator('#clubTeams input').fill('Unsere Erste');await page.locator('#clubPublished').check();await page.getByRole('button',{name:'Vereinsangaben speichern',exact:true}).click();await page.getByText('Vereinsangaben gespeichert.',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Darts-Seite',exact:true}).click();assert.equal(await page.locator('#dartsLeagues fieldset').count(),0,'new clubs never inherit Barver sources');await page.getByRole('button',{name:'+ Liga hinzufügen',exact:true}).click();await page.locator('[name=source-url]').fill('https://portal.3k-darts.com/frontend/events/10/event/123/phase/456');await page.locator('[name=source-name]').fill('Unsere Liga');await page.getByRole('button',{name:'Verbindung prüfen',exact:true}).click();await page.getByText('18 Spieltage gefunden. Wähle jetzt die 3K-Mannschaften aus.',{exact:true}).waitFor();await page.locator('[data-source-team]').selectOption('789');await page.getByRole('button',{name:'Verbindung prüfen',exact:true}).click();await page.locator('#dartsStatus').filter({hasText:'18 Spieltage'}).waitFor();assert.equal(await page.locator('[data-source-team]').inputValue(),'789','checking a link preserves selected assignments');await page.locator('#dartsEnabled').check();await page.getByRole('button',{name:'Darts-Einrichtung speichern',exact:true}).click();await page.getByText('Darts-Einrichtung gespeichert. Der Server übernimmt die regelmäßige Aktualisierung.',{exact:true}).waitFor();assert.equal(clubs[1].darts.leagues[0].assignments[0].participant_id,789);assert.equal(await page.locator('#publicGames').getAttribute('href'),'/vereine/musterverein/darts');
    await page.getByRole('button',{name:'Zugänge',exact:true}).click();await page.locator('#userForm input[name=username]').fill('redaktion');await page.locator('#userForm input[name=password]').fill('fixture-redaktion-password');await page.getByRole('button',{name:'Zugang anlegen',exact:true}).click();await page.getByText('Redakteurszugang angelegt.',{exact:true}).waitFor();assert.equal(await page.locator('#userForm input[name=password]').inputValue(),'');
    await page.getByRole('button',{name:'+ Verein hinzufügen',exact:true}).click();await page.locator('#newClubForm input[name=name]').fill('Dartclub Beispielstadt');assert.equal(await page.locator('#newClubForm input[name=slug]').inputValue(),'dartclub-beispielstadt');await page.getByRole('button',{name:'Verein anlegen',exact:true}).click();await page.locator('#clubLabel').filter({hasText:'Dartclub Beispielstadt'}).waitFor();await page.getByText('Verein angelegt. Ergänze die Angaben und gib die Seite frei, wenn alles bereit ist.',{exact:true}).waitFor();assert.equal(clubs[2].published,false,'new club sites start private');
    await page.getByRole('button',{name:'Übersicht',exact:true}).click();for(const theme of ['light','dark']){if(await page.getAttribute('html','data-theme')!==theme)await page.locator('#themeToggle').click();for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'CMS fits '+width+' in '+theme);await page.getByRole('button',{name:'Beiträge',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'editor fits '+width);await page.getByRole('button',{name:'Übersicht',exact:true}).click();}}
    if(process.env.CMS_MOBILE_SCREENSHOT)await page.screenshot({path:process.env.CMS_MOBILE_SCREENSHOT});
    await page.goto(origin+'/vereine/musterverein');await page.getByRole('heading',{name:'Musterverein',exact:true}).waitFor();assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--link').trim()),'#182b24','light club colors keep links readable');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    posts[0].publishAt=new Date(Date.now()-60000).toISOString();posts[0].published.title=hostile;await page.goto(origin+'/vereine/barver/beitraege/1');await page.locator('#siteArticle').waitFor();assert.match(await page.locator('#siteArticle h1').innerText(),/onerror/);assert.equal(await page.evaluate(()=>window.cmsXss),undefined);assert.deepEqual(errors,[]);
    console.log('CMS browser checks passed: login, drafts, preview, publication, conflicts, schedules, revisions, club separation, editor creation, team-only published posts, club team setup, verified league mapping, 320/390px themes and safe public content.');
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
