const assert=require('node:assert/strict');
const source=require('../static/darts-source-fallback.js');
const now=Date.now(),league={key:'kl04',event:1445,phase:2139,name:'KL',short:'KL',teams:{174110:'A'}};
const raw={id:1,statusCd:'FINISH',setsHome:4,setsAway:8,participantHome:{id:174110,displayName:'Barver A',email:'private'},participantGuest:{id:2,displayName:'Gäste',phone:'private'},datePlanned:new Date(now-86400000).toISOString()};
const item=source.normalize(raw,league,3,now);
assert.equal(item.kind,'final');assert.equal(item.score,'4:8');assert.equal(item.text,'Gäste gewinnt 8:4 gegen Barver A');
assert.ok(!JSON.stringify(item).includes('private'));
assert.equal(source.normalize({...raw,byeAway:true},league,3,now),null);
assert.equal(source.normalize({...raw,participantHome:{id:9}},league,3,now),null);
const pending=source.normalize({...raw,statusCd:'OPEN',setsHome:null,setsAway:null},league,3,now);
assert.equal(pending.kind,'pending');assert.equal(pending.score,null);
const live=source.liveEvents({data:[{id:7,statusActive:true,currentplayerIndex:1,matchPlayers:[{playerName:'A',points:121,legs:2,darts:12,dartsTotal:27,scoreTotal:880,lastScore:57,email:'private'},{playerName:'B',points:5000,legs:1,score:180}]}]},item);
assert.equal(live[0].homeRemaining,121);assert.equal(live[0].awayRemaining,null);assert.equal(live[0].currentSide,'away');
assert.equal(live[0].home.darts,12);assert.equal(live[0].home.totalDarts,27);assert.equal(live[0].home.totalScore,880);assert.equal(live[0].home.lastScore,57);assert.equal(live[0].home.average,97.8);assert.equal(live[0].away.average,null);
assert.ok(!JSON.stringify(live).includes('private'));assert.deepEqual(source.liveEvents({data:[{statusActive:false,matchPlayers:[]}]},item),[]);
const rounds=[{id:1,dateFrom:new Date(now-86400000).toISOString()},{id:2,dateFrom:new Date(now+86400000).toISOString()},{id:3,dateFrom:new Date(now+10*86400000).toISOString()}];
assert.deepEqual(source.relevantRounds(rounds,now).map(r=>r.id),[1,2]);
let calls=0;
global.fetch=async(url,options)=>{
  calls++;assert.equal(options.credentials,'omit');assert.ok(!options.headers.Authorization);
  assert.match(url,/^https:\/\/(backend-ddv|live)\.3k-darts\.com\//);
  if(url.includes('/round/'))return {ok:true,json:async()=>({matches:[{...raw,statusCd:'FINISH'}]})};
  return {ok:true,json:async()=>({rounds})};
};
(async()=>{
  const [first,second]=await Promise.all([source.load(),source.load()]);
  assert.equal(first,second);assert.equal(calls,6,'parallel callers share one bounded fetch');
  assert.equal(first.source,'browser-3k');assert.equal(first.stale,false);
  await source.load();assert.equal(calls,6,'avoid repeated upstream requests within 30 seconds');
  const visited=[];
  const future={...raw,id:9,eventId:1445,statusCd:'OPEN',setsHome:null,setsAway:null,datePlanned:new Date(now+86400000).toISOString()};
  global.fetch=async(url,options)=>{visited.push(url);assert.equal(options.credentials,'omit');return {ok:true,json:async()=>({matches:[future]})};};
  const fixture=await source.loadMatch({id:9,eventId:1445,roundId:3,homeVenue:{street:'Testweg 4'}});
  assert.equal(fixture.match.kind,'upcoming');assert.equal(fixture.reportAvailable,false);assert.equal(fixture.match.homeVenue.street,'Testweg 4');
  assert.equal(visited.length,1,'upcoming fixture does not require a report');
  await source.loadMatch({id:9,eventId:1445,roundId:3});assert.equal(visited.length,1,'reuse recently verified fixture');
  await assert.rejects(source.loadMatch({id:9,eventId:999,roundId:3}),/Unsupported/);
  const past={...raw,id:10,eventId:1445};
  global.fetch=async url=>({ok:true,json:async()=>url.includes('/round/')?{matches:[past]}:url.includes('/performance/')?[{performanceTypeCd:'HS',value:180,participant:{displayName:'Heim',email:'private'}}]:[{id:7,gameNr:1,statusCd:'FINISH',legsHome:1,legsAway:3,participantHome:{displayName:'Heim',score:450,darts:30,email:'private'},participantGuest:{displayName:'Gast',phone:'private'}}]});
  const report=await source.loadMatch({id:10,eventId:1445,roundId:3});
  assert.equal(report.reportAvailable,true);assert.equal(report.games[0].home.average,45);assert.equal(report.games[0].awayLegs,3);assert.equal(report.performances[0].type,'180');
  assert.ok(!JSON.stringify(report).includes('private'));
  global.fetch=async()=>({ok:true,json:async()=>({matches:[{...past,id:11,participantHome:{id:888},participantGuest:{id:999}}]})});
  await assert.rejects(source.loadMatch({id:11,eventId:1445,roundId:3}),/does not belong/);
  const entries=[{participantId:174110,participantName:'Barver A',participantRankingPos:3,placement:'1.',matchCount:3,win:2,tie:1,lost:0,points1:5,points2:1,sets1:24,sets2:12,legs1:70,legs2:41,email:'private'}, {participantId:888,participantName:'Gast',participantRankingPos:1,placement:'2.',points1:6,points2:0,phone:'private'}];
  const table={tableEntries:[{tableEntries:entries}]};
  assert.deepEqual(source.officialStandings(table,league).map(row=>row.rank),[1,2],'use current placements, not participant seeds or local points sorting');
  const tied={tableEntries:[{tableEntries:[...entries,{...entries[1],participantId:889,placement:'2.'},{...entries[1],participantId:890,placement:null}]}]};
  assert.deepEqual(source.officialStandings(tied,league).map(row=>row.rank),[1,2,2,null],'preserve ties and missing places');
  for(const value of [null,false,true,0,-1,'0.','-2.','2abc','1.-2.',''])assert.equal(source.tablePlacement(value),null);
  assert.equal(source.tablePlacement(' 2. '),2);
  assert.equal(source.officialStandings(table,league)[1].played,null,'missing values are not invented');
  let tableFails=false,roundFails=false;const centerCalls=[];
  global.fetch=async(url,options)=>{
    centerCalls.push(url);assert.equal(options.credentials,'omit');
    if(url.endsWith('/table'))return {ok:!tableFails,json:async()=>table};
    if(url.includes('/round/'))return {ok:!roundFails,json:async()=>({matches:[future,{...future,id:12,participantHome:{id:777,displayName:'Fremder Verein'}}]})};
    return {ok:true,json:async()=>({rounds:[{id:3,name:'Spieltag 3',dateFrom:new Date(now-1000).toISOString(),dateTo:new Date(now+86400000).toISOString()},{id:4,name:'Spieltag 4'}]})};
  };
  const center=await source.loadCenter('kl04',3);
  assert.equal(center.source,'browser-3k');assert.equal(center.matches.length,2,'include all league fixtures');assert.equal(center.barverMatches.length,1);
  assert.equal(center.standings.length,2);assert.equal(center.standings[0].pointsFor,5);assert.ok(!JSON.stringify(center).includes('private'));
  await source.loadCenter('kl04',3);assert.equal(centerCalls.length,3,'bounded league polling');
  await assert.rejects(source.loadCenter('foreign',3),/Unsupported/);
  await assert.rejects(source.loadCenter('kl04',999),/does not belong/);
  tableFails=true;const partial=await source.loadCenter('kl04',4);
  assert.equal(partial.matches.length,2);assert.equal(partial.standingsUnavailable,true);assert.equal(partial.degraded,true);
  tableFails=false;roundFails=true;const tableOnly=await source.loadCenter('kl04',4);
  assert.equal(tableOnly.matchesUnavailable,true);assert.equal(tableOnly.standings.length,2,'standings recover independently of schedule');
  tableFails=true;await assert.rejects(source.loadCenter('kl04',4),/unavailable/);
  const aborted=new AbortController();aborted.abort();await assert.rejects(source.loadCenter('kl04',3,aborted.signal),/cancelled/);
  const playerRows=[{displayName:'Jannik Kläning',team:{name:'SV Barver Darts A'},scoreTotal:11421,dartsTotal:520,matchesTotal:6,matchesWon:6,legCount:18,legCountOpponent:5,count180:3,checkoutMax:91,email:'private'}, {displayName:'Jannik Kläning & Zweiter Spieler',team:{name:'SV Barver Darts A'}}, {displayName:'Jannik Kläning',team:{name:'Anderer Verein A'},phone:'private'}];
  global.fetch=async(url,options)=>{assert.equal(options.credentials,'omit');return {ok:true,json:async()=>url.includes('/1445/statistics')?playerRows:[]};};
  const playerStats=await source.loadPlayerStats([{id:89027,name:'Jannik Kläning',team:'A'}]);
  assert.equal(Object.keys(playerStats.players).length,1);assert.equal(playerStats.players['89027'].average,65.9);assert.equal(playerStats.players['89027'].gamesPlayed,6);assert.equal(playerStats.players['89027'].count180,3);assert.equal(playerStats.statsSchema,1);assert.equal(playerStats.stale,false);assert.ok(!JSON.stringify(playerStats).includes('private'));
  global.fetch=async url=>{if(url.includes('/1460/'))throw new Error('offline');return {ok:true,json:async()=>playerRows};};
  const partialStats=await source.loadPlayerStats([{id:89027,name:'Jannik Kläning',team:'A'}]);assert.equal(partialStats.degraded,true);assert.equal(partialStats.players['89027'].average,65.9);
  global.fetch=async()=>{throw new Error('offline');};await assert.rejects(source.loadPlayerStats([]),/unavailable/);
  console.log('3K fallback: public allowlist, verified player stats, real scores and bounded polling OK');
})().catch(error=>{console.error(error);process.exitCode=1});
const sourceEnded={id:8,statusActive:true,statusFinished:false,mode:'Best of 5 Legs',matchPlayers:[{playerName:'Jannik',points:64,legs:1},{playerName:'Robin',points:0,legs:3}]};
assert.equal(source.liveEvents({data:[sourceEnded]},item).length,0,'fallback also drops a completed best-of-five game');
assert.equal(source.liveEvents({data:[{...sourceEnded,mode:'Best of 7 Legs'}]},item).length,1);
assert.equal(source.liveEvents({data:[{...sourceEnded,mode:'',statusFinished:true}]},item).length,0);
